[workspace]

members = [
  "contracts/hyp-erc20",
  "libraries/hyperlane-connection-client",
  "libraries/hyperlane-gas-router",
  "libraries/hyperlane-router",

  "tests/hyperlane-connection-client-test",
  "tests/hyperlane-router-test",

  "mocks/mock-interchain-gas-paymaster",
  "mocks/mock-mailbox",
]
