[project]
authors = ["Trevor Porter"]
entry = "lib.sw"
license = "Apache-2.0"
name = "hyperlane_gas_router"

[dependencies]
hyperlane_connection_client = { path = "../hyperlane-connection-client" }
hyperlane_interfaces = { git = "https://github.com/hyperlane-xyz/fuel-contracts", rev = "8423fd3" }
hyperlane_router = { path = "../hyperlane-router" }
