[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "hyp-erc20"

[dependencies]
hyperlane_connection_client = { path = "../../libraries/hyperlane-connection-client" }
hyperlane_gas_router = { path = "../../libraries/hyperlane-gas-router" }
hyperlane_interfaces = { git = "https://github.com/hyperlane-xyz/fuel-contracts", rev = "8423fd3" }
hyperlane_router = { path = "../../libraries/hyperlane-router" }
ownership = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.8.0" }
