[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "hyp-erc20"

[dependencies]
hyperlane_connection_client = { path = "../../libraries/hyperlane-connection-client" }
hyperlane_gas_router = { path = "../../libraries/hyperlane-gas-router" }
# hyperlane_interfaces = { git = "https://github.com/hyperlane-xyz/fuel-contracts", rev = "71e6d37" }
hyperlane_interfaces = { path = "/Users/trevor/fuel-contracts/contracts/hyperlane-interfaces" }
hyperlane_router = { path = "../../libraries/hyperlane-router" }
# ownership = { git = "https://github.com/fuellabs/sway-libs", rev = "f6c4cb7" }
ownership = { path = "/Users/trevor/.forc/git/checkouts/ownership-f6c4cb75510d36fd/f6bb5c234e020d556e1bc688e0f1f368dc9b0f9a/libs/ownership" }
token_interface = { path = "../../libraries/token-interface" }
token_router = { path = "../../libraries/token-router" }
